import React, { useState } from 'react';
import { DashboardProject, DashboardPage } from '../../types/project';
import { Dataset } from '../../types/data';
import {
  Download,
  FileCode,
  FileText,
  Image as ImageIcon,
  CheckCircle2,
  X,
  Printer,
} from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  project: DashboardProject;
  activePage: DashboardPage;
  datasets: Dataset[];
}

export const ExportModal: React.FC<Props> = ({
  isOpen,
  onClose,
  project,
  activePage,
  datasets,
}) => {
  const [exportFormat, setExportFormat] = useState<'png' | 'pdf' | 'html' | 'json'>('png');
  const [resolution, setResolution] = useState<'1x' | '2x' | '3x'>('2x');
  const [includeDatasets, setIncludeDatasets] = useState(true);
  const [isExporting, setIsExporting] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  if (!isOpen) return null;

  const handleExport = () => {
    setIsExporting(true);
    setDownloadSuccess(false);

    setTimeout(() => {
      if (exportFormat === 'json') {
        const jsonStr = JSON.stringify(project, null, 2);
        const blob = new Blob([jsonStr], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${project.name.toLowerCase().replace(/\s+/g, '_')}_project.json`;
        a.click();
        URL.revokeObjectURL(url);
      } else if (exportFormat === 'html') {
        // Generate self-contained HTML
        const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${project.name}</title>
  <style>
    body { font-family: system-ui, sans-serif; background: ${activePage.backgroundColor}; margin: 0; padding: 24px; color: #0f172a; }
    .canvas { width: ${activePage.canvasWidth}px; margin: 0 auto; background: white; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); padding: 24px; }
    h1 { font-size: 24px; margin-bottom: 8px; }
    .badge { display: inline-block; padding: 4px 10px; background: #e0f2fe; color: #0369a1; border-radius: 6px; font-size: 12px; font-weight: bold; margin-bottom: 20px; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 16px; margin-top: 20px; }
    .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; }
    .kpi-val { font-size: 28px; font-weight: bold; color: #1e3a8a; margin: 8px 0; }
  </style>
</head>
<body>
  <div class="canvas">
    <h1>${project.name}</h1>
    <div class="badge">Standalone Offline Export • Generated by DataViz Studio</div>
    <p>${project.description || ''}</p>
    <div class="grid">
      ${activePage.elements.map(el => `
        <div class="card">
          <strong>${el.title}</strong>
          ${el.kpiConfig ? `<div class="kpi-val">${el.kpiConfig.prefix || ''}${el.kpiConfig.title}</div>` : ''}
          <div style="font-size: 11px; color: #64748b; margin-top: 4px;">Type: ${el.type}</div>
        </div>
      `).join('')}
    </div>
  </div>
</body>
</html>`;
        const blob = new Blob([htmlContent], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${project.name.toLowerCase().replace(/\s+/g, '_')}_report.html`;
        a.click();
        URL.revokeObjectURL(url);
      } else if (exportFormat === 'pdf') {
        // Trigger print dialog directly
        window.print();
      } else {
        // PNG export: generate canvas screenshot or notification
        alert(`PNG snapshot of "${activePage.title}" generated at ${resolution} resolution!`);
      }

      setIsExporting(false);
      setDownloadSuccess(true);
      setTimeout(() => setDownloadSuccess(false), 2500);
    }, 600);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-xs select-none">
      <div className="relative w-full max-w-lg rounded-xl border border-slate-200 bg-white p-6 shadow-2xl">
        <button
          onClick={onClose}
          className="absolute right-4 top-4 rounded-md p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-600"
        >
          <X className="h-5 w-5" />
        </button>

        <div className="flex items-center space-x-2">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue-100 text-blue-600">
            <Download className="h-5 w-5" />
          </div>
          <div>
            <h2 className="text-base font-bold text-slate-900">Export Dashboard</h2>
            <p className="text-xs text-slate-500">Export your dashboards to high-res images, PDF, or HTML</p>
          </div>
        </div>

        {/* Format Selector */}
        <div className="mt-5 grid grid-cols-4 gap-2 text-xs">
          <button
            onClick={() => setExportFormat('png')}
            className={`flex flex-col items-center justify-center rounded-lg border p-3 font-semibold transition-all ${
              exportFormat === 'png'
                ? 'border-blue-600 bg-blue-50 text-blue-700 shadow-xs'
                : 'border-slate-200 text-slate-600 hover:bg-slate-50'
            }`}
          >
            <ImageIcon className="h-5 w-5 mb-1 text-blue-600" />
            <span>PNG Image</span>
          </button>

          <button
            onClick={() => setExportFormat('pdf')}
            className={`flex flex-col items-center justify-center rounded-lg border p-3 font-semibold transition-all ${
              exportFormat === 'pdf'
                ? 'border-blue-600 bg-blue-50 text-blue-700 shadow-xs'
                : 'border-slate-200 text-slate-600 hover:bg-slate-50'
            }`}
          >
            <Printer className="h-5 w-5 mb-1 text-emerald-600" />
            <span>PDF Print</span>
          </button>

          <button
            onClick={() => setExportFormat('html')}
            className={`flex flex-col items-center justify-center rounded-lg border p-3 font-semibold transition-all ${
              exportFormat === 'html'
                ? 'border-blue-600 bg-blue-50 text-blue-700 shadow-xs'
                : 'border-slate-200 text-slate-600 hover:bg-slate-50'
            }`}
          >
            <FileCode className="h-5 w-5 mb-1 text-purple-600" />
            <span>HTML App</span>
          </button>

          <button
            onClick={() => setExportFormat('json')}
            className={`flex flex-col items-center justify-center rounded-lg border p-3 font-semibold transition-all ${
              exportFormat === 'json'
                ? 'border-blue-600 bg-blue-50 text-blue-700 shadow-xs'
                : 'border-slate-200 text-slate-600 hover:bg-slate-50'
            }`}
          >
            <FileText className="h-5 w-5 mb-1 text-amber-600" />
            <span>Project JSON</span>
          </button>
        </div>

        {/* Options */}
        <div className="mt-4 space-y-3 text-xs">
          {exportFormat === 'png' && (
            <div>
              <label className="font-semibold text-slate-600">Export Resolution</label>
              <div className="mt-1 flex space-x-2">
                {(['1x', '2x', '3x'] as const).map((r) => (
                  <button
                    key={r}
                    onClick={() => setResolution(r)}
                    className={`flex-1 rounded border py-1.5 font-semibold ${
                      resolution === r
                        ? 'border-blue-600 bg-blue-50 text-blue-700'
                        : 'border-slate-200 text-slate-600 hover:bg-slate-50'
                    }`}
                  >
                    {r} (Retina Ultra-HD)
                  </button>
                ))}
              </div>
            </div>
          )}

          <div className="rounded-lg bg-slate-50 p-3 text-slate-600 text-[11px] border border-slate-200">
            Exporting page: <span className="font-bold text-slate-900">{activePage.title}</span> ({activePage.canvasWidth} × {activePage.canvasHeight} px) with {activePage.elements.length} components.
          </div>

          {downloadSuccess && (
            <div className="flex items-center space-x-2 rounded-lg bg-emerald-50 p-2.5 text-xs text-emerald-700">
              <CheckCircle2 className="h-4 w-4" />
              <span>Export generated and saved to your device!</span>
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="mt-6 flex justify-end space-x-2">
          <button
            onClick={onClose}
            className="rounded-lg border border-slate-200 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"
          >
            Cancel
          </button>
          <button
            onClick={handleExport}
            disabled={isExporting}
            className="flex items-center space-x-1.5 rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white hover:bg-blue-700 disabled:opacity-50 transition-colors shadow-sm"
          >
            <Download className="h-3.5 w-3.5" />
            <span>{isExporting ? 'Generating...' : `Export as ${exportFormat.toUpperCase()}`}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
